version: 2

jobs:
  build:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run:
          command: npm run build
      - run:
          command: |
            mkdir /tmp/artefacts
            zip -r dist.zip dist
            cp dist.zip
      - store_artifacts:
          path: /tmp/artefacts
