version: 2

jobs:
  build:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run:
          command: |
            apk add python make g++ zip
            npm install
            npm run build
      - run:
          command: |
            mkdir /tmp/artefacts
            zip -r dest.zip dest/
            cp dist.zip
      - store_artifacts:
          path: /tmp/artefacts
